# Generated by Django 3.2.5 on 2021-08-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_Name', models.CharField(max_length=30)),
                ('event_Date', models.DateField(default='2000-10-12')),
                ('starting_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('venue', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('event_link', models.URLField()),
            ],
        ),
    ]
