# Generated by Django 3.2.5 on 2021-08-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('course_code', models.CharField(max_length=20)),
                ('course_channel', models.CharField(max_length=20)),
                ('course_trainer', models.CharField(max_length=20)),
                ('course_description', models.CharField(max_length=100)),
                ('course_syllabus', models.CharField(max_length=20)),
            ],
        ),
    ]
