# Generated by Django 3.2.5 on 2021-08-13 16:04

import django.core.validators
from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=12)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.PositiveSmallIntegerField()),
                ('date_of_birth', models.DateField(default='2000-10-12')),
                ('phone_number', models.CharField(max_length=20)),
                ('admission_date', models.DateField(default='2000-10-12')),
                ('guardian_name', models.CharField(max_length=20)),
                ('id_number', models.CharField(max_length=20)),
                ('nationality', models.CharField(choices=[('KENYAN', 'KENYAN'), ('UGANDAN', 'UGANDAN'), ('SUDAN', 'SUDAN'), ('RWANDESE', 'RWANDESE')], default='KENYAN', max_length=20)),
                ('class_name', models.CharField(blank=True, max_length=20, null=True)),
                ('medical_report', models.FileField(upload_to='files/')),
                ('email', models.EmailField(max_length=254)),
                ('academic_year', models.IntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1984), student.models.max_value_current_year])),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='FEMALE', max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
